name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Execute Script
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: chmod +x build.sh && bash build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: alpat.zst
