
name: Build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Execute Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./build.sh
          ./build.sh
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: zippy.zip
